Update README.md's IRC channels link
ipfs/ipfs pull request #467
Opened 2021-06-04 14:29 UTC by yaodzy

The current link of IRC channels in README.md is https://docs.ipfs.io/community/irc/ , which is already 404 (Oops, this page has moved or no longer exists). 

I believe the correct link should be https://webchat.freenode.net/?channels=ipfs , so submit this PR.

2021-06-04 17:56 UTC, profi200 commented
In case the channel is indeed still on freenode i would recommend moving over to https://libera.chat because all the staff moved over after a hostile takeover. If this project still cares about IRC that is.

2021-06-04 18:38 UTC, Clay-Ferguson commented
> In case the channel is indeed still on freenode i would recommend moving over to https://libera.chat because all the staff moved over after a hostile takeover. If this project still cares about IRC that is.

Supposedly there's also a Matrix bridge which allows any libera.chat (or freenode?) room to work thru Matrix? I'm not enough of an expert on Matrix to know, but I though it worth mentioning here.

2021-06-04 19:46 UTC, aschmahmann requested changes
Thanks for the ping to update here. The primary IPFS chats now happen on Matrix and has some bridges (e.g. to Discord).

2021-06-04 19:46 UTC, aschmahmann commented on README.md
> +The IPFS project is big — with thousands of contributors in our community — and you're invited to join! Check out the [Community section of the IPFS Docs](https://docs.ipfs.io/community/) for all the
How about

```suggestion
The IPFS project is big — with thousands of contributors in our community — and you're invited to join! Check out the [Community section of the IPFS Docs](https://docs.ipfs.io/community/) for all the details on how to get involved, including the official [IPFS forums](https://discuss.ipfs.io), our [chat channels](https://docs.ipfs.io/community/chat), [social media](https://docs.ipfs.io/community/social-media), [meetups and ProtoSchool workshops](https://github.com/ipfs/community#events), and more.
```

2021-06-08 00:34 UTC, yaodzy commented on README.md
> +The IPFS project is big — with thousands of contributors in our community — and you're invited to join! Check out the [Community section of the IPFS Docs](https://docs.ipfs.io/community/) for all the
Agree, this looks better. :)

2021-06-18 09:23 UTC, yaodzy commented
@aschmahmann , I have updated README.md according to your suggestion. Please have a look, thanks.

2021-06-24 17:13 UTC, Stebalien approved these changes

2021-06-24 17:13 UTC, merged